### ISSUE TITLE
checked out chapter 6 and couldn't get it working

### ISSUE THREAD

**Issue by bjameshunter** [lightweightdjango/examples#14]
After spending a lot of time matching my code with the book and this repo (not quite identical) I just checked out chapter 6 and couldn't get it working. Honestly, I haven't read the whole chapter, as I started following the repo once I couldn't get the sprints to show up by the first live example (section "Using the Client State").

Anyway, I got a 500 error when posting to api/tasks. 

It's been going just great up until now. Is this just me? I'll dig a little deeper, but this is my first time using backbone, so it's all a little foggy.

Thanks,
Ben

**Comment by mlavin** [comment]
Haven't seen any related errata but it ight be a regression from the REST Framework 3 updates we made. @juliaelman and I can do some digging.

**Comment by mlavin** [comment]
This appears to be another change from REST framework 2.4 -> 3.X. The serializer sees the default value on that `status` field and marks it as non-required; however, it doesn't use the default value as it previously was doing. When the client sends the request to add a new task it only sends `{name: "fail", description: ""}` and `int(attrs.get('status'))` fails because `attrs.get` returns `None` rather than the expected default of `Task.STATUS_TODO`.

A more welcome change according to the release notes is that the `int` call should no longer be needed http://www.django-rest-framework.org/topics/3.0-announcement/#serializer-fields

> The previous field implementations did not forcibly coerce returned values into the correct type in many cases. For example, an IntegerField would return a string output if the attribute value was a string. We now more strictly coerce to the correct return type, leading to more constrained and expected behavior.

Changing 

```
status = int(attrs.get('status'))
```

to 

```
status = attrs.get('status', Task.STATUS_TODO)
```

in the`TaskSerializer.validate` method appears to fix this issue. I'll do some more testing and add an errata and update this repo. Thank for the report!

**Comment by mlavin** [comment]
Errata created and updated the repo branches to reflect this change.
